[package]
name = "my-custom-manager"
version = "0.0.8"
authors = ["Your Name <your@email.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
zellij-tile = { path = "../../zellij-tile" }
serde = { version = "1.0", features = ["derive"] }